### ISSUE TITLE
Not recognising default object exports

### ISSUE THREAD

**Issue by ajaymathur** [preconstruct/preconstruct#104]
For a file like:

```
function log() {}
export default { log }
```

The build dist files does not default export eg-`export {default} from ...` and have a * export like - `export * from`

Tried default export function and then it works perfect.

Please do let me know if anymore information is needed, re-producible example is needed or anything that I can help with. 🙂 ❤️

**Comment by mitchellhamilton** [comment]
A reproduction would be very helpful. I just tried to reproduce it and it seemed it work correctly

**Comment by ajaymathur** [comment]
Hey @mitchellhamilton , sorry that I bothered you in morning. I tried it again and it seems to be working. I am not 100% sure now what what went wrong at that time. My apologies.
