### ISSUE TITLE
Explore what TypeScript support should look like 

### ISSUE THREAD

**Issue by mitchellhamilton** [preconstruct/preconstruct#19]

**Comment by lukebatchelor** [comment]
G'day!

I'd be super keen to help out with this if that's cool. 

I'm looking at using this in [Atlaskit](https://bitbucket.org/atlassian/atlaskit-mk-2) soon and around half of the packages there are TS.

**Comment by mitchellhamilton** [comment]
> I'd be super keen to help out with this if that's cool.

That would be awesome!

> I'm looking at using this in Atlaskit soon and around half of the packages there are TS.

I should have updated this issue but TS files can now be resolved and compiled with Babel using `@babel/preset-typescript`, would that work for Atlaskit or does Atlaskit use [TS features that require the actual TS compiler](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats)?

Another thing I'd like preconstruct to do with TS though is generate a bundle with all of the type declarations and add the `types` package.json field. preconstruct does a similarish thing with flow right now where it generates `.flow` files which re-export from the source file. I'm guessing generating an actual declaration file would be possible with TS though. Would that be useful for Atlaskit?

**Comment by lukebatchelor** [comment]
> or does Atlaskit use TS features that require the actual TS compiler?

I believe there is one or two that do, but we're planning on fixing those soon. 

Perfect, I'll give this a shot and write up some doc's for it I'd you like

**Comment by mitchellhamilton** [comment]
Some docs would be great

**Comment by mitchellhamilton** [comment]
#59
