### ISSUE TITLE
UMD builds don't work with libraries that support browserify / use process.browser

### ISSUE THREAD

**Issue by scottsidwell** [preconstruct/preconstruct#235]
👋 Hope you're having a great day

---
## Background

I recently tried to enable UMD builds for a new package I was releasing, and I ran into this error:
```
"tty" is imported by "../../node_modules/debug/src/node.js" but
it is not specified in dependencies or peerDependencies
```

Going to the affected file revealed that the `debug` module was doing:
```
if (typeof process === 'undefined' || process.type === 'renderer' || process.browser === true || process.__nwjs) {
  module.exports = require('./browser.js');
} else {
  module.exports = require('./node.js');
}
```

So this failed because it tried to evaluate the Node imports, but `tty` is a built-in Node module so it wasn't listed in the package.json.

This works in webpack, because webpack will set `process.browser = true` as part of polyfill-ing any references to Node in a browser bundle. (https://github.com/webpack/node-libs-browser/blob/master/mock/process.js#L12)

This is also used by `browserify` (https://github.com/defunctzombie/node-process & https://github.com/browserify/browserify/blob/master/package.json#L54)

I suspect there's a number of browserify-compatible packages using this approach that'd fail to build in preconstruct because it attempts to require the Node version

---
## Options

So there's a couple of options here (that I can see):
1. Add a rollup plugin to set this to true `replace({ 'process.browser': true })`
2. Pull in another package that solves this problem more thoroughly https://github.com/calvinmetcalf/rollup-plugin-node-globals
3. Do nothing? :) 

I'd be happy to help with the PR since it should be relatively straight-forward either way, but I'll leave it up you to decide the direction we should take 👍

**Comment by scottsidwell** [comment]
I've pushed up a repository with an example here: https://github.com/scottsidwell/preconstruct-umd-process-browser-example

**Comment by mitchellhamilton** [comment]
I don't think that would really fix it since rollup-plugin-commonjs would still import that module(I think)

Could you try adding `replace({ 'process.browser': true, include: ["**/node_modules/**", "node_modules/**"] })` and see if it works? If it works, I'm happy to add it.

**Comment by scottsidwell** [comment]
👋 just an update on my progress on this.

Just replacing `process.browser` in the relevant node_modules doesn't resolve the issue, as some (naughty) dependencies expect that things like `Buffer` will be appropriately polyfilled / shimmed into the bundle which this rollup config to do.

For any issue archaeologists from the future:
Updating the config to use https://github.com/calvinmetcalf/rollup-plugin-node-globals somewhat resolved this, however it was still fragile so ultimately I switched to using preconstruct for the main bundles, and webpack to on-demand build the UMD I needed before publishing to NPM.

Thanks for your help looking into this 🤜🤛
