### ISSUE TITLE
source file not found `typescript-declarations` PLUGIN_ERROR

### ISSUE THREAD

**Issue by mrmartineau** [preconstruct/preconstruct#236]
Currently Preconstruct cannot build one of the entrypoints in my package (see the error message below). I have figured out what file is causing the issue, but not why the issue is being caused - does that make sense? Would it be possible to improve the feedback in the CLI so that debugging can be improved?

See below, the key part is on the 2nd line `source file not found` but it does not specify what source file..

```
🎁 info building bundles!
🎁 error my-design-system Error: This is an internal error, please open an issue if you see this: source file not found
🎁 error my-design-system     at searchDeps (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:881:34)
🎁 error my-design-system     at Object.getDeps (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:890:8)
🎁 error my-design-system     at Object.generateBundle (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:912:122) {
🎁 error my-design-system   code: 'PLUGIN_ERROR',
🎁 error my-design-system   plugin: 'typescript-declarations',
🎁 error my-design-system   hook: 'generateBundle'
🎁 error my-design-system }
```

Here is the source code that generated that error: https://github.com/preconstruct/preconstruct/blob/c4886ea432a839291437c3346ddc6253b462c918/packages/cli/src/rollup-plugins/typescript-declarations/create-generator.ts#L125-L155

By tweaking the source code in `node_modules` like below, I see that the problem file is displayed. So it would be great to generate an error message that included that path.

```diff
            throw new Error(
-              "This is an internal error, please open an issue if you see this: source file not found"
+             dep
            );
```

This now shows an error like so: 

```
🎁 info building bundles!
🎁 error my-design-system Error: /Users/my-design-system/src/themes/index.js
🎁 error my-design-system     at searchDeps (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:881:34)
🎁 error my-design-system     at Object.getDeps (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:890:8)
🎁 error my-design-system     at Object.generateBundle (/Users/my-design-system/node_modules/@preconstruct/cli/cli/dist/cli.cjs.prod.js:912:122) {
🎁 error my-design-system   code: 'PLUGIN_ERROR',
🎁 error my-design-system   plugin: 'typescript-declarations',
🎁 error my-design-system   hook: 'generateBundle'
🎁 error my-design-system }
```

But it obviously still isn't very helpful because it only shows the error on the entrypoint itself, not the actual file that is causing the error.

I will investigate this further and try to create a PR with a fix, but for now, @mitchellhamilton is adding more fidelity to errors something you're keen on?

**Comment by mitchellhamilton** [comment]
Could you make it throw a `FatalError` and change the error message to `Could not generate type declarations because ${dep} does not exist or is not a TypeScript file`?

**Comment by mrmartineau** [comment]
Sure, I'll do it today
