### ISSUE TITLE
Support Yarn v2 (PnP)

### ISSUE THREAD

**Issue by tunnckoCore** [preconstruct/preconstruct#237]
This could be interesting. Currently it doesn't work and I'm trying to figure out how to build/bundle if I'm using Yarn PnP... Raw Rollup works fine, even without the "promoted" `rollup-plugin-pnp-resolve` (with it fails https://github.com/arcanis/rollup-plugin-pnp-resolve/issues/5). But the cool thing about `preconstruct` is the "dev" command "linking", so I probably should fallback to my approach that we discussed, by using the `node-resolve` customResolveOptions hacks, which in turn I'm guessing won't work either. So probably we should wait for `mainFields` implementation and something like "packageFilter" inside the `pnp-resolve` plugin.

**Comment by mitchellhamilton** [comment]
Could you share what error you're currently getting with Yarn PnP?

**Comment by efoken** [comment]
With Yarn 2 when running `preconstruct build`, I'm alway getting an error, that Typescript should be installed:

```sh
🎁 error @test/core an entrypoint source file ends with the .ts or .tsx extension but the typescript module could not be resolved from the project directory, please install it.
```

The `preconstruct dev` command is working as expected.
