### ISSUE TITLE
Consider including scope name in the generated filenames

### ISSUE THREAD

**Issue by Andarist** [preconstruct/preconstruct#244]
As mentioned in emotion repo - after package renaming our `@emotion/react` will have a confusing file name because it will be shortened to just "react".

I can implement a change if you give a green light on this one.

**Comment by mitchellhamilton** [comment]
I'm open to this but I don't think it should happen now since it'll be a breaking change, we'll also probably want to include a hyphenated form of the path to entrypoint if it's not at the root. I'm guessing Preconstruct will have a major version soonish though because of Node ESM.

**Comment by Andarist** [comment]
Sure - let me know when you are going to work on next major version and I'll try to do my best to help you out.

**Comment by Andarist** [comment]
Related issue, that I think it would be great to fix together with this, is that currently additional entries don't have their entry names in the filename, which more often than not is something that wasnt expected:

An example of this can be found here:
https://github.com/emotion-js/emotion/blob/4aacba54cdc65ac50bec57d8211a62fe65b6b1f7/packages/styled/base/package.json

**Comment by mitchellhamilton** [comment]
Agreed
