### ISSUE TITLE
how to solve the problem of '#! /usr/bin/env node'

### ISSUE THREAD

**Issue by FengShangWuQi** [preconstruct/preconstruct#248]
if the app is a cli, how to solve the problem of '#! /usr/bin/env node'

**Comment by mitchellhamilton** [comment]
You can create a file like this which imports the entrypoint for the cli
```js
#!/usr/bin/env node

require(".");
```

For example, Preconstruct itself does this:

https://github.com/preconstruct/preconstruct/blob/afdc895e8bbae3344212245dc6aed297f0f3a7e4/packages/cli/bin.js#L1-L4
