### ISSUE TITLE
Ability to ignore package

### ISSUE THREAD

**Issue by maraisr** [preconstruct/preconstruct#250]
We have a monorepo that also contains our renovate config so that it can be shareable. Now renovate insist config be stored in the package.json. So this "package" contains nothing but a package.json, however preconstruct complains about "no source file was provided".

Would be rad if this tool will allow a "ignore" option, for preconstrct to treat it as a nothing.

**Comment by mitchellhamilton** [comment]
You can ignore a package with globs. E.g. in your root packag.json
```json
{
  "preconstruct": ["packages/*", "!packages/some-package"]
}
```
