### ISSUE TITLE
TypeScript projects break on Windows

### ISSUE THREAD

**Issue by maraisr** [preconstruct/preconstruct#256]
When building a fresh repo using typescript on Windows. I've got path problems.

https://github.com/preconstruct/preconstruct/blob/e50769a843f827292bdf94dd52cb26be31f0fc1c/packages/cli/src/rollup-plugins/typescript-declarations/index.ts#L49-L56

where;

```plaintext
facadeModuleId == C:\Users\me\Sites\github\abc\packages\123\src\index.ts

srcFilenameToDtsFilenameMap == Map(1) {
  'C:/Users/me/Sites/github/abc/packages/123/src/index.ts' => 'C:/Users/me/Sites/github/abc/packages/123/src/index.d.ts'
}
```

as you can see, the indexes of the Map will never equal.

**Comment by NateRadebaugh** [comment]
I've also hit this issue. Where's the right place to do the conversion?

`facadeModuleId` is a rollup concept, so I imagine it should not be changed. So it looks like some combination of `globby` and `path` that is creating conflicting paths.

**Comment by NateRadebaugh** [comment]
I spent some time trying to convert the internal paths to be consistent, but am fighting with `globby`, `path`, and `resolve.sync` to the extent that I'm not sure if it's worth it, and is counterproductive to convert things to normal string concats.

I think the best bet would be to use something like https://github.com/jonschlinkert/normalize-path before comparison/map lookup

@mitchellhamilton thoughts?

**Comment by mitchellhamilton** [comment]
Using normalize-path sgtm

**Comment by NateRadebaugh** [comment]
k cool, fix incoming
