### ISSUE TITLE
getDeclarationFile function failing and triggering error

### ISSUE THREAD

**Issue by sidneyramos** [preconstruct/preconstruct#271]
Builds are failing because getDeclarationFile can't get `output.outputFiles[0].name` 

one solution that I thought about was changing the function to have a condition to check if there is an `output.outputFiles[0]` object

```
getDeclarationFile: async filename => {
    if (filename.endsWith(".d.ts")) {
        return {
            name: filename.replace(dirname, path.join(dirname, "dist", "declarations")),
            content: await fs.readFile(filename, "utf8")
        };
    } else {
        let output = service.getEmitOutput(filename, true);
        if (output.emitSkipped) { //checks if output.outputFiles[0]
            return {
                name: filename.replace(dirname, path.join(dirname, "dist", "declarations")),
                content: await fs.readFile(filename, "utf8")
            };
        } else {
            const outputFile = output.outputFiles[0];
            return {
                name: outputFile.name.replace(dirname, path.join(dirname, "dist", "declarations")),
                content: outputFile.text
            };
        }
    }
}
```

**Comment by evocateur** [comment]
I hit the same problem (possibly triggered by `export type { FooType } from './foo';` in my entry point?), and found the solution in https://github.com/microsoft/TypeScript/commit/850d16e45f3292749c8d9d662b2bd7395ab1d881:
https://github.com/preconstruct/preconstruct/blob/e50769a843f827292bdf94dd52cb26be31f0fc1c/packages/cli/src/rollup-plugins/typescript-declarations/create-generator.ts#L174
```diff
-      let output = service.getEmitOutput(filename, true);
+      let output = service.getEmitOutput(filename, true, true);
```
Adding the `forceDtsEmit` flag ensures that `outputFile.name` always exists, thus avoiding the null reference error.

**Comment by mitchellhamilton** [comment]
@evocateur want to submit a PR?

**Comment by evocateur** [comment]
@mitchellhamilton Opened!

Guess I have to learn how to make a changeset now...
