### ISSUE TITLE
Add a flag to add a version to the generated filename

### ISSUE THREAD

**Issue by Andarist** [preconstruct/preconstruct#286]
This might not make enough sense to be included here, but it's an idea I had and thought that it might be worth sharing here.

We got a report about Jest's cache not being busted when upgrading our Babel plugin/preset - https://github.com/emotion-js/emotion/issues/1593 - and this sometimes causing snapshots to pass even though they shouldnt anymore because generated hashes should have been changed.

The problem is that Jest is computing a cache key from loaded (but not fully resolved) Babel config so if it doesn't recognize the change/upgrade then it won't rerun tests. I've bumped into this myself many times but just dealt with it by busting cache manually with `--no-cache`.

So the idea is that if we would be able to add a version to generated filenames by preconstruct then this cache could be busted automatically because the content of the serialized Babel config would change (it's a loaded config that is being used as part of the cache key and it contains resolved filenames of presets/plugins). This, of course, wouldn't cover for all cases - because it would just include a version of a top-level package and not its dependencies, but it would at least make the issue pop up less often.

**Comment by mitchellhamilton** [comment]
Don't really think this is something we should do given that would mean we would have to update the package.json fields on every new version which would get pretty annoying quickly.
