### ISSUE TITLE
How to setup preconstruct dev with create react app?

### ISSUE THREAD

**Issue by lokhmakov** [preconstruct/preconstruct#287]
I find @preconstruct/next where:

* rootMode changed to "upward-optional"
* from webpack rules with default babel loader removed include

Right now we installed CRA, react-app-rewired and customize-cra on top of it for possibility to change webpack and babelrc.

**Comment by mitchellhamilton** [comment]
Yep, so you need to make it so Babel has `upward-optional` so that Babel finds the config at the root of your project and that all files except anything in node_modules is compiled by Babel(By default, I believe CRA only runs Babel on files outside of node_modules and in the app's directory).
