### ISSUE TITLE
Unable to export types from source files.

### ISSUE THREAD

**Issue by timothymathison** [preconstruct/preconstruct#288]
### Description
I'm having issues defining a `type` in my `.ts` source file and exporting it via the `index.ts` file.

#### To Reproduce:

With the following directory structure:
```
|-- src/
    |-- components
        |-- Foo
            |-- Foo.tsx
            |-- index.ts
```

`Foo.tsx`
```tsx
export type FooType = 'Foo' | 'Foo2'
```
`index.ts`
```ts
import { FooType } from './Foo';
export { FooType };
```

__Result:__
```shell
$ preconstruct build
🎁 info building bundles!
🎁 error my-package An unhandled Rollup error occurred: src/components/Foo/index.ts Non-existent export 'FooType' is imported from src/components/Foo/Foo.tsx
```

__Expected Result:__ The `type` should be exported and included in the declaration files which are generated.

**Comment by lokhmakov** [comment]
@timothymathison 

```js
import {FooType} from './Foo'

export type {FooType}
```

**Comment by timothymathison** [comment]
@lokhmakov Thanks! My issue was not including `type` in the import line.

**Comment by mitchellhamilton** [comment]
Thanks for answering @lokhmakov!

If anyone's curious why you need to do this, it's because Preconstruct uses Babel which only compiles files on their own, without any context of other modules so you need to add `type` to let Babel know that it's a type import and should therefore be removed.
