### ISSUE TITLE
Dev builds are not working with React Native/Expo app in monorepo

### ISSUE THREAD

**Issue by efoken** [preconstruct/preconstruct#300]
I use a monorepo to build a design system for iOS, Android and Web and I have an Expo app inside this monorepo (using expo-yarn-workspaces and stuff). Then I tried to import components into my Expo app and got the following error:

```
Failed building JavaScript bundle.
You attempted attempted to import the Node standard library module "path" from "../core/dist/core.cjs.js". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries
```

Makes sense, because React Native is not supporting built-in Node libraries. What I've tried is using a package called `node-libs-react-native`, but it doesn't work too – I get:

```
Unable to resolve "module" from "../../node_modules/pirates/lib/index.js"
```

Next I also tried to polyfill "module" with the `module` npm package. But then Metro Bundler is complaining about source-map-support, that does not work, because `fs` is missing...

```
The package at "../../node_modules/source-map-support/source-map-support.js" attempted to import the Node standard library module "fs". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries
````

...

**Comment by efoken** [comment]
BTW, without this `@preconstruct/hook` in `core.cjs.js` dev build it does work, so I guess that should be optional ?!

**Comment by ifiokjr** [comment]
@efoken In the `package.json` for the packages have you tried setting the `module` field?

```diff
  "main": "dist/core.cjs.js",
+ "module": "dist/core.esm.js",
```

The `react-native` metro bundler can be [configured to resolve](https://facebook.github.io/metro/docs/configuration#resolvermainfields) the `module` field (if it doesn't do so already). I'm not sure if `expo` has this built in or if there is a way to configure it.

**Comment by johno** [comment]
FWIW I was experiencing this with a Gatsby project (in a monorepo) where I was importing a Preconstruct-built package that didn't have a `module` field. Stumbled upon this and @ifiokjr's [comment](https://github.com/preconstruct/preconstruct/issues/300#issuecomment-671210709) which got me sorted out.

Would be great to catch this error somehow and log something out to better direct users to a fix. It's pretty cryptic.

Thanks for the great work! Love Preconstruct.
