### ISSUE TITLE
Glob exclusions in multiple entrypoints

### ISSUE THREAD

**Issue by sarahbethfederman** [preconstruct/preconstruct#324]
Any chance there might be support added for exclude patterns in the globs for entrypoints? I have an icons package and I'd like to be able to import like `@lendi-ui/icon/IconName` but I can't just add `*` for the entrypoints without including `dist` and `src` and whatnot. I suppose I could write a script that goes and adds each folder to the entrypoints array individually, but it would be nice if I didn't have to 😅

**Comment by mitchellhamilton** [comment]
You can use `!` before a glob to do an exclusion - e.g.

```json
{
  "preconstruct": {
    "entrypoints": [
      "*",
      "!whatever-you-want"
    ]
  }
}
```

**Comment by sarahbethfederman** [comment]
Ah, I thought the * was implied in the exclusion, works when I added it. Thanks!

**Comment by sarahbethfederman** [comment]
Not strictly related but I'm having a fun problem now where I need to have built out my assets for `preconstruct dev` to work so that the source files pointed at in the entrypoints exist, but my asset build pipeline requires `preconstruct dev` to have been run so that it can find the private package with my babel plugin 😅 any advice?

**Comment by mitchellhamilton** [comment]
Not a great solution but I'd say probably install `@babel/register` and create a file like this:

```js
require("@babel/register")

module.exports = require('./path/to/package/src')
```

and then add it to your babel config like this so that it doesn't run on itself:

```json
{
  "overrides": [{
    "test": "./wherever/the/stuff/you/want/to/run/your/babel/plugin/is",
    "plugins": ["./wherever/the/file/you/created/above/is"]
  }]
}
```

**Comment by sarahbethfederman** [comment]
Hm, I'm not sure I understand. The babel plugin is created in one package and required by the config for svgr (not a babel-config) in another. It's separate from my root babel config. I'm not sure where the code in your example should go/point to?
```
utils/babel-plugin-wrapper <-- private package @lendi-ui/babel-plugin-wrapper
packages/icon/svgr.config.js <-- package @lendi-ui/icon which requires @lendi-ui/babel-plugin-wrapper to build assets
```
I suppose I could just publish it as a workaround, but it's for internal use so I was hoping not to

**Comment by mitchellhamilton** [comment]
ah, I assumed the babel plugin was for your babel config, you should be able to do something like this then in your svgr.config.js:

```js
require("@babel/register")({ extensions: [".tsx", ".ts", ".js"], rootMode: "upward-optional" })
const babelPluginWrapper= require("@lendi-ui/babel-plugin-wrapper/src")

// whatever else you want in your babel config
```

**Comment by sarahbethfederman** [comment]
That worked thank you!!
I'm having another issue now though, where the entrypoints for the icon package are correct, but the main entrypoint is not. The "main" field points to "dist/icon.cjs.js", but the main dist folder for icon is generating chunks like "packages/icon/dist/Icon-5352584b.cjs.dev.js"

Manypkg check and preconstruct validate aren't bringing up any issues. I'm not sure if I'm setting up entrypoints incorrectly

**Comment by sarahbethfederman** [comment]
Oh, nvm looks like I needed "." in addition to "*" in my entrypoints

**Comment by sarahbethfederman** [comment]
Hey @mitchellhamilton this exclusion pattern seems to have broken when upgrading from 1.1.27 to latest

**Comment by sarahbethfederman** [comment]
Seems to be working again switching from 
```
  "preconstruct": {
    "entrypoints": [
      ".",
      "*",
      "!(dist|src|build-scripts|node_modules)"
    ]
  },
```
to
```
  "preconstruct": {
    "entrypoints": [
      ".",
      "!(dist|src|build-scripts|node_modules)"
    ]
  },
```

**Comment by mitchellhamilton** [comment]
Hmm, interesting that removing the `*` makes it work. I switched from using globby to directly using fast-glob(which globby uses) which is probably the reason it broke so I've just published `@preconstruct/cli@1.1.33` which reverts the change.

**Comment by sarahbethfederman** [comment]
I think that fast-glob is using the more common configuration where ! means "all things that match except this", which seems more correct? This is where my original problem came from https://github.com/preconstruct/preconstruct/issues/324#issuecomment-700348646

**Comment by sarahbethfederman** [comment]
https://github.com/micromatch/micromatch#extglobs

**Comment by mitchellhamilton** [comment]
Yeah, I agree, just wanted to change it back to not break people's current globs. I'll probably change to fast-glob directly in a major version

**Comment by sarahbethfederman** [comment]
makes sense, thanks!
