### ISSUE TITLE
strange build failure from uncooperating dependency

### ISSUE THREAD

**Issue by pkieltyka** [preconstruct/preconstruct#339]
Hello,

please see the following monorepo using preconstruct: https://github.com/pkieltyka/0xsequence.js

to reproduce error:

```
1. yarn install
2. yarn build
```

results in:

https://gist.github.com/pkieltyka/671e55a9024548f38f9442cc01f4c6a6

---

the dependency `ethers` from https://github.com/ethers-io/ethers.js is a monorepo built with typescript and compiled with rollup. The package targets node and browsers, and offers a meta-package "ethers" with most of the sub-packages under "@ethersproject/xxx"

there are many issues with "ethers" to work under preconstruct. Here are the few.

1. First issue is I had to specifically add `@ethersproject/providers` to the dependencies list or preconstruct would complain: https://github.com/pkieltyka/0xsequence.js/blob/master/packages/provider/package.json#L25-L26. This is strange as `@ethersproject/providers` is a dependency of `ethers` already, so I'd hope that preconstruct could infer this list -- if this is a design decision, then please consider this a feature request as it's quite unwieldy in the current form.

2. as you can see in this gist, https://gist.github.com/pkieltyka/671e55a9024548f38f9442cc01f4c6a6 -- the build blows up. It appears as though it's trying to build this with "node" targets, but im targetting a browser. This particular log also has the issue of `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten` warnings, which I'm not sure why they're happening.

---

all of this is to say, that the identical source code builds perfectly fine if I just use `rollup -c` using a very simple rollup config https://gist.github.com/pkieltyka/d11b0fd8f7d83ac581fba39a9bfdbfcb

also FYI, microbundle has almost the identical problems as I tried to use it as well. 

I could just use rollup directly and skip preconstruct, but I like a lot of the extra utilities it offers

**Comment by pkieltyka** [comment]
FYI, https://github.com/ethers-io/ethers.js/issues/998 I came across this issue in the dependency which is being problematic. It seems others are having similar issues with webpack 5, but found ways to get around it. Just wanted to provide that info in case it helps solve around these issues in preconstruct when dependencies become challenging

**Comment by Andarist** [comment]
@mitchellhamilton I'll take a look at this one and report back when I get more info

**Comment by Andarist** [comment]
Do you need a UMD bundle for this? I would suspect that you don't need it - so just to execute `build` successfully you could apply this patch:
```diff
diff --git a/packages/0xsequence/package.json b/packages/0xsequence/package.json
index 7c05aa8..d00cd97 100644
--- a/packages/0xsequence/package.json
+++ b/packages/0xsequence/package.json
@@ -12,10 +12,7 @@
   },
   "peerDependencies": {},
   "keywords": [],
-  "umd:main": "dist/0xsequence.umd.min.js",
-  "preconstruct": {
-    "umdName": "0xsequence"
-  },
+  "preconstruct": {},
   "files": [
     "src",
     "dist"
```

**Comment by pkieltyka** [comment]
@Andarist I was just about to leave you comment about the very same thing! I had discovered it was the umd build to be causing these issues.

However, I do need the umd build as well.

Here is a rollup.config.js that actually builds with the umd but specifying the ethers stuff as externals:

```
  {
    input: pkg.source,
    output: [
      {
        file: pkg['umd:main'],
        format: 'umd',
        name: '0xsequence',
        globals: null
      },
    ],
    external: [
      'ethers',
      '@ethersproject/providers',
      '@ethersproject/wallet',
      '@ethersproject/properties',
      '@ethersproject/web',
      '@ethersproject/json-wallets',
      '@ethersproject/hash'
    ],
    plugins: [
      typescript({
        typescript: require('typescript'),
        useTsconfigDeclarationDir: true,
        tsconfigOverride: {
          compilerOptions: {
            outDir: "./dir",
            declarationDir: "./dist/declarations"
          }
        }
      }),
      json(),
      resolve({
        browser: true
      }),
      commonjs({
        browser: true
      }),
      terser()
    ]
  }
```

is it possible in package.json under "preconstruct" to pass some of these options..? noteably, `browser: true` and `externals`. In the end however, I'd like to try to figure out how to package ethers with the umd as well, but keeping it external can work for now anyways.

thank you

**Comment by Andarist** [comment]
Control over externals should not be needed (unless proven otherwise) - in your case `browser: true` is required though. Maybe this should even be a default for UMDs? UMD doesn't necessarily say anything about the target environment but they are mainly used for browsers. @mitchellhamilton WDYT?

Additionally this set of ignored warnings should be extended with `"THIS_IS_UNDEFINED"`:
https://github.com/preconstruct/preconstruct/blob/be053e75d6b2793ee220f537eb0506a948874fea/packages/cli/src/build/rollup.ts#L88-L93
This could be done only for UMDs as then we bundle files out of our control - this might still be a worthwhile error for direct source files 🤔 

And finally - this should be fixed: https://github.com/ethers-io/ethers.js/pull/1137

When I've fixed manually all of those directly in node_modules I've managed to get `preconstruct build` execute successfully.

**Comment by mitchellhamilton** [comment]
> browser: true is required though. Maybe this should even be a default for UMDs? UMD doesn't necessarily say anything about the target environment but they are mainly used for browsers

Yeah, we already assume that UMD builds are for browsers. 👍  to adding browser: true

> Additionally this set of ignored warnings should be extended with "THIS_IS_UNDEFINED":
>  This could be done only for UMDs as then we bundle files out of our control - this might still be a worthwhile error for direct source files 🤔

sgtm

**Comment by Andarist** [comment]
I've already prepared PRs for the things recognized in [this comment](https://github.com/preconstruct/preconstruct/issues/339#issuecomment-722709084):
- https://github.com/preconstruct/preconstruct/pull/340
- https://github.com/preconstruct/preconstruct/pull/343

The third issue got reported to The Ethers Project and is being discussed there - this one is out of our hands. So I believe this issue can be closed now.
