### ISSUE TITLE
More info on Error

### ISSUE THREAD

**Issue by joeysherman** [preconstruct/preconstruct#355]
I come here from keystone, thank you for all the hard work you all do.

I encountered this error while trying to build the latest master branch. Fresh install and everything.

![Code_QCmP534wMo](https://user-images.githubusercontent.com/18039561/101406004-bf8a7b00-388d-11eb-95c8-53101902b96a.png)

Thus when I try to run the dev project.

![Code_r9td8S8EQS](https://user-images.githubusercontent.com/18039561/101406661-99190f80-388e-11eb-8795-d091ccf2fa38.png)

This happens on 2 separate laptops, both running windows. Node version 12.19.1 and yarn 1.22.10

**Comment by mitchellhamilton** [comment]
This was fixed in https://github.com/preconstruct/preconstruct/commit/c2a9918ee73f5900f6c5b9a96c2efd94299ab416
