### ISSUE TITLE
`@babel/runtime/helpers` are imported but not specified during build

### ISSUE THREAD

**Issue by makezi** [preconstruct/preconstruct#356]
I've tried setting up a monorepo for a react component library following the [monorepo.guide](https://monorepo.guide/getting-started) getting started guide and hit an issue when attempting to do a build:

`error @components-test/box "@babel/runtime/helpers/toConsumableArray" is imported by "src/index.js" but the package is not specified in dependencies or peerDependencies`

Which is caused by the following code (`/packages/box/index.js`):

```javascript
import styled from '@emotion/styled';
import { padding } from 'styled-system';
import {
  createShouldForwardProp,
  props as styledSystemProps
} from '@styled-system/should-forward-prop';

// Plan to add more custom style props here
const shouldForwardProp = createShouldForwardProp([...styledSystemProps]);

const Box = styled('div', { shouldForwardProp })`
  box-sizing: border-box;
  min-width: 0;

  ${padding}
`;

export default Box;
```

`babel.config.js`:

```javascript
module.exports = {
  presets: [
    '@babel/preset-env',
    [
      '@babel/preset-react',
      {
        // Have a nextjs project for docs with the new JSX transform
        runtime: 'automatic'
      }
    ]
  ],
  plugins: ['@emotion', '@babel/plugin-transform-runtime']
};
```

root `package.json`:

```json
{
  // omitted...
  "dependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "@changesets/cli": "^2.12.0",
    "@emotion/babel-plugin": "^11.1.2",
    "@manypkg/cli": "^0.16.1",
    "@preconstruct/cli": "^2.0.1",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.2.2",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "prettier": "^1.19.1",
    "react": "^17.0.1",
   // omitted...
  }
}

```

As the error suggests, adding `@babel/runtime` to `packages/box` works but don't want to do this for every package. Adding it to the root `package.json` does not however. Am I missing some configuration within `babel.config.js`? I noticed within the preconstruct source code that it does include `@babel/runtime`.

Also to note that this is reproducible with the [monorepo-starter](https://github.com/Thinkmill/monorepo-starter) as well:

`error @monorepo-starter/graphql-api "@babel/runtime/helpers/taggedTemplateLiteral" is imported by "src/index.js" but the package is not specified in dependencies or peerDependencies`

Apologies if I missed something obvious.

**Comment by mitchellhamilton** [comment]
> As the error suggests, adding @babel/runtime to packages/box works but don't want to do this for every package

You need to either add @babel/runtime or remove @babel/plugin-transform-runtime. See https://babeljs.io/docs/en/babel-plugin-transform-runtime#why for an explanation of why using @babel/plugin-transform-runtime is ideal

**Comment by makezi** [comment]
Thanks for the response @mitchellhamilton. I see that emotion also uses preconstruct and imports [@babel/runtime for their packages](https://github.com/emotion-js/emotion/blob/2f9ce557df6974aafd8d515fbe676ebae6df6e36/packages/react/package.json#L29). 

So to be 100% certain, if this were the case, shouldn't the [graphql-api package](https://github.com/Thinkmill/monorepo-starter/blob/master/services/graphql-api/package.json) in the monorepo-starter be updated to include `@babel/runtime` in its dependencies as well? If so, can close this issue and set up a PR over there to include it.

Thanks again.

**Comment by mitchellhamilton** [comment]
Yes, that's correct, the graphql-api package should have a dependency on @babel/runtime. A PR would be great!

**Comment by makezi** [comment]
[Done.](https://github.com/Thinkmill/monorepo-starter/pull/23) Closing the issue!
