### ISSUE TITLE
Allow Babel config based on babelrc files

### ISSUE THREAD

**Issue by Andarist** [preconstruct/preconstruct#360]
Currently, Babel only knows about the root of the project:
https://github.com/preconstruct/preconstruct/blob/764bb9b05851bf88ecc62179628a8d1ff1ac26f8/packages/cli/src/worker.ts#L48-L49
and thus it can't resolve non-root configs. It would be great to have `babelrcRoots` configured properly for packages or at least add some docs that this is a limitation of preconstruct (or a deliberate design decision). If this won't get supported a helpful validation would also be great.

**Comment by mitchellhamilton** [comment]
Hmmm, that's interesting, this wasn't a deliberate decision. I'll have a look

**Comment by mitchellhamilton** [comment]
As discussed in https://github.com/preconstruct/preconstruct/pull/371#issuecomment-785438082, this is now intentionally not done, you can use `babelrcRoots` in the root Babel config
