### ISSUE TITLE
Module not found: Can't resolve '../../../node_modules/@preconstruct/hook' in monorepo

### ISSUE THREAD

**Issue by cmaycumber** [preconstruct/preconstruct#365]
When using `precontruct dev` I'm currently getting the following error because preconstruct is pointing to the improper location for `@preconstruct/hooks`.

I'm not sure if my configuration is wrong, but I noticed that if I change to the directory to one step higher from `../../../node_modules/@preconstruct/hook` to `../../../../node_modules/@preconstruct/hook` inside of the `.cjs.js` file for any given package my webpack is able to resolve it. 

My current project structure using preconstruct looks like this (with packages being top level):

**package folder**: `packages/package1`
**dist location**: `packages/package1/dist`

The `.cjs.js` file is created under the dist as would be expected.

Any help on this would be great. Thanks for a great package!

**Comment by mitchellhamilton** [comment]
Could you provide a reproduction?

**Comment by cmaycumber** [comment]
Yes, I'll try to put something together!

**Comment by cmaycumber** [comment]
I'm going to close this. I wasn't able to reproduce it and was trying to use `preconstruct` with an expo/react-native monorepo, so the configuration of that may have been my problem.

Thanks for the prompt response.
