### ISSUE TITLE
Preconstruct watch not working properly with entrypoints

### ISSUE THREAD

**Issue by dbismut** [preconstruct/preconstruct#375]
Hi, I'm currently building this monorepo library https://github.com/dbismut/preconstruct-repro and chose `preconstruct` as the build tool. Fantastic experience so far I love it.

I'm having a bug though, with `preconstruct watch` modifying my own code. I've made a minimum repro showing the issue:
https://github.com/dbismut/preconstruct-repro

Just run `yarn preconstruct watch` and look at what happens inside the file inside `src/utils/index.js`.

```js
// what I wrote
export { fn2 } from "../data";

// how preconstruct watch alters it:

// at first:
export { f as fn2 } from '../../dist/data-11edc36a.esm.js';
// and then:
function fn2() {
  return 3;
}

export { fn2 };
```
 
I'm guessing this has to do with the secondary entry point exporting a file which is also consumed by the main entry point in `src/index.js`?

EDIT: forgot to mention that `preconstruct build && preconstruct watch` solves it in my case.

**Comment by Andarist** [comment]
Thanks for the report - I might take a look at it soon-ish but no hard promises

**Comment by dbismut** [comment]
Thanks @Andarist, just spotted your answer now. Btw, in dev mode, I have an issue with relative imports from the esm.js source file that can't be resolved. Is this something that you're aware of? I can also file an issue for this.

**Comment by Andarist** [comment]
Please create a repro case for that other case and open a new issue for it. As to this issue here - I've managed to prepare a fix: https://github.com/preconstruct/preconstruct/pull/376
