### ISSUE TITLE
Build errors for type exports

### ISSUE THREAD

**Issue by jrolfs** [preconstruct/preconstruct#391]
Hi, I'm pretty keen to move a monorepo project over from TSDX to Preconstruct, but am currently stuck on some `preconstruct build` errors. It seems to be throwing the following error for any `type` or `interface` exports:

```
🎁 error @hover/blueprint An unhandled Rollup error occurred: packages/components/src/components/Slider/Slider.tsx (18:9) Non-existent export 'SliderProps' is imported from packages/components/src/components/Slider/types.ts
```

I've shuffled some of the exports around to see if that particular export was the issue and keep running into similar cases (always for `type` or `interface` exports):

```
🎁 info building bundles!
🎁 error @hover/blueprint Error: 'BlockOptionProps' is not exported by packages/components/src/components/BlockOption/index.tsx, imported by packages/components/src/index.ts
🎁 error @hover/blueprint     at error (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:5305:30)
🎁 error @hover/blueprint     at Module.error (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:9750:16)
🎁 error @hover/blueprint     at Module.getVariableForExportName (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:9910:29)
🎁 error @hover/blueprint     at Module.includeAllExports (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:9991:35)
🎁 error @hover/blueprint     at Graph.includeStatements (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:19357:24)
🎁 error @hover/blueprint     at Graph.build (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:19291:14)
🎁 error @hover/blueprint     at runMicrotasks (<anonymous>)
🎁 error @hover/blueprint     at processTicksAndRejections (internal/process/task_queues.js:97:5)
🎁 error @hover/blueprint     at async rollupInternal (/Users/jamie/Developer/Hover/blueprint/node_modules/rollup/dist/shared/rollup.js:20240:9)
🎁 error @hover/blueprint     at async /Users/jamie/Developer/Hover/blueprint/node_modules/@preconstruct/cli/cli/dist/cli.cjs.dev.js:2196:18 {
🎁 error @hover/blueprint   code: 'MISSING_EXPORT',
🎁 error @hover/blueprint   url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
🎁 error @hover/blueprint   id: '/Users/jamie/Developer/Hover/blueprint/packages/components/src/index.ts',
🎁 error @hover/blueprint   pos: 968,
🎁 error @hover/blueprint   loc: {
🎁 error @hover/blueprint     file: '/Users/jamie/Developer/Hover/blueprint/packages/components/src/index.ts',
🎁 error @hover/blueprint     line: 25,
🎁 error @hover/blueprint     column: 2
🎁 error @hover/blueprint   },
🎁 error @hover/blueprint   frame: '23: export {\n' +
🎁 error @hover/blueprint     '24:   default as BlockOption,\n' +
🎁 error @hover/blueprint     '25:   BlockOptionProps,\n' +
🎁 error @hover/blueprint     '      ^\n' +
🎁 error @hover/blueprint     "26: } from './components/BlockOption';\n" +
🎁 error @hover/blueprint     "27: export { default as Slider, SliderProps } from './components/Slider';",
```

My `babel.config.js`:

```js
module.exports = {
  presets: [
    '@babel/preset-typescript',
    '@babel/preset-react',
    '@babel/preset-env',
  ],
};
```

I'll try to make some time to set up a minimal reproduction repo, but am curious if I'm doing something stupid or whether this is a known issue.

**Comment by mitchellhamilton** [comment]
Preconstruct uses Babel to compile TypeScript code so you have to use `export type` instead of `export` so that Babel knows the export can be removed.

**Comment by jrolfs** [comment]
Shouldn't `@babel/preset-typescript` handle that, though?

**Comment by mitchellhamilton** [comment]
It can't handle certain cases like this because it doesn't have type information when compiling:
```tsx
import { SomeType } from 'somewhere'

export { SomeType };
```

**Comment by jrolfs** [comment]
Got it, that makes sense. I'll revisit that branch shortly and see if I can handle those cases explicitly.

Thanks for the prompt responses!

**Comment by jrolfs** [comment]
I'm surprised I haven't run into this before as I do use Babel to compile TypeScript in other projects but I guess this library is the only place that I've forwarded type exports like this.

The trick seems to be setting `isolatedModules: true` on the TypeScript compiler. While I understand this is out of the purview of Preconstruct, do you think it's worth adding a note to the "Building TypeScript packages" section of the documentation? I'd be happy to open a PR. I was also surprised not to see that compiler option mentioned in the Babel documentation at all.

Thanks again!

**Comment by jrolfs** [comment]
Ah, I jumped the gun. It is referenced here: https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options

**Comment by mitchellhamilton** [comment]
> do you think it's worth adding a note to the "Building TypeScript packages" section of the documentation? I'd be happy to open a PR

that would be great!

**Comment by jrolfs** [comment]
#392
