### ISSUE TITLE
Using Node builtin modules results in "package is not specified in dependencies or peerDependencies" error

### ISSUE THREAD

**Issue by garrettjstevens** [preconstruct/preconstruct#401]
I'm trying to add a second entrypoint that is server side code that depends on some modules which aren't available for the browser (like it says on [this page](https://preconstruct.tools/guides/when-should-i-use-multiple-entrypoints)). However, when I use one of those modules (for example `fs`), I get the error:

```
🎁 error preconstruct-testing "fs" is imported by "src/create.ts" but the package is not specified in dependencies or peerDependencies
```

Could that check also be widened to include dep, peerDeps, and also Node builtins? Or is there some other way to use Node builtin modules?

**Comment by mitchellhamilton** [comment]
Node builtins should already be allowed, could you create a reproduction in a GitHub repo?

**Comment by garrettjstevens** [comment]
Sorry, user error on that one. I thought I had gotten rid of the "browser" field in my package.json, but apparently it was still there. Now that I've removed it, everything works as expected. Thanks.
