### ISSUE TITLE
How to configure .npmrc to publish private packages to a private repository

### ISSUE THREAD

**Issue by WangShuXian6** [preconstruct/preconstruct#438]
```npmrc
registry=http://nexus.demo.com/repository/npm-local/
email=airmusic@msn.com
always-auth=true
_auth="xxxxxxxxxxxxxx=" // base64加密的用户名+密码
```
>Note: The registry and _auth values are processed 

>The above configuration works fine when publishing a single package, 
>but when publishing monorepo it prompts 
```bash
error an error occurred while publishing @demo/core: ENEEDAUTH This command requires you to be logged in. 
🦋  error You need to authorize this machine using `npm adduser`
🦋  error <Buffer 6e 70 6d 20 45 52 52 21 20 63 6f 64 65 20 45 4e 45 45 44 41 55 54 48 0a 6e 70 6d 20 45 52 52 21 20 6e 65 65 64 20 61 75 74 68 20 54 68 69 73 20 63 6f ... 420 more bytes>
🦋  error packages failed to publish:
🦋  @demo/core@0.0.2
error Command failed with exit code 1.
```

>I have added the following configuration to each `package.json` file
```JSON
  "publishConfig": {
    "registry": "http://nexus.demo.com/repository/npm-local/"
  }
```

>As an alternative, running the following command will append a private repository license to the global npmrc file, so you can distribute monorepo packages normally.
```bash
npm login --registry=http://nexus.demo.com/repository/npm-local/
```

>But I want to automate the release of monorepo packages in the pipeline, so I want to prioritize using the npmrc file for authorization

>Does this project support reading the user license from the npmrc file to distribute packages?

**Comment by mycroes** [comment]
This is unrelated to preconstruct; preconstruct has nothing to do with publishing. Personally I'm using a monorepo with yarn. I have publishConfig.registry set to the registry in all my packages (as you have) and a yarnrc in my CI environment for the credentials, that works just fine. I used to publish with npm before, same story.
