### ISSUE TITLE
Run task in a package

### ISSUE THREAD

**Issue by moklick** [preconstruct/preconstruct#482]
Hey! 

Is it possible to run a task in package? In our case we want to copy some css to the dist folder of a certain package. We would like to run the task after the build task but only for one specific package.

**Comment by efoken** [comment]
You can achieve this using NPM scripts using workspaces. For example you could add a `build` script to certain packages and execute them from the root when `preconstruct build` is finished.

For example when you use Yarn you can use something like this in your root package.json:

```json
"scripts": {
  "build": "preconstruct build",
  "postbuild": "yarn workspaces @your-package/containing-a-build-script build"
}
```
