### ISSUE TITLE
Optional peer dependencies not considered in validation

### ISSUE THREAD

**Issue by lucasecdb** [preconstruct/preconstruct#493]
If you build a package `a` using `preconstruct dev` that **only** depends on another package `b`, and this package `b` specifies an _optional_ peerDependency on package `c`, preconstruct throws an error saying that package `a` is missing a dependency on package `c`.

This shouldn't be the case, since package `c` is specified as optional in package `b` manifest. This should be taken in consideration when validating the dependencies.

**Comment by with-heart** [comment]
@lucasecdb Is there any way you could create a reproduction? I tried creating one locally and couldn't reproduce the issue

**Comment by with-heart** [comment]
Hi @lucasecdb, I tried reproducing this locally and was unable to cause the same error. Here's a link to my reproduction: https://github.com/with-heart/preconstruct-optional-dependencies-reproduction

Could you create a reproduction of the issue you're seeing, so we can figure out what's specific to your setup that might be causing this problem?

**Comment by lucasecdb** [comment]
sure @with-heart! I'll try to create a minimal repo with the reproduction

**Comment by with-heart** [comment]
> sure @with-heart! I'll try to create a minimal repo with the reproduction

Awesome! ty

btw thanks for the detailed issue description. I felt inspired to record myself creating that reproduction (https://www.loom.com/share/41402f2e523a40b3a5110f28d3d70ec2), so thanks for inspiring me ❤️

**Comment by lucasecdb** [comment]
@with-heart I just uploaded the repro here https://github.com/lucasecdb/preconstruct-repro

while doing that, I found out that this error only happens if you have the following configuration in package `a`:

```json
{
  "preconstruct": {
    "umdName": "a"
  }
}
```

I think this was why it didn't happen in your repository

**Comment by lucasecdb** [comment]
I think we may be missing a check here if the dependency is optional, but I don't really know if there is larger implications because the package needs to be bundled as UMD

https://github.com/preconstruct/preconstruct/blob/0c794551a9158136fce27db576630d8461e44e24/packages/cli/src/validate-package.ts#L152

**Comment by with-heart** [comment]
@lucasecdb Yeap, adding `umd:main` and `preconstruct.umdName` now causes the error
