### ISSUE TITLE
VSCode auto imports from "package/dist/declarations/src/component" instead of "package/component"

### ISSUE THREAD

**Issue by RossMcMillan92** [preconstruct/preconstruct#519]
Hey there,

Love preconstruct so far! Looking for a bit of guidance as I've ran into an issue with my package with multiple entry points.

My config looks something like this:

``` json
"preconstruct": {
  "exports": true,
  "entrypoints": [
    "components/Form/Form.tsx",
    "hooks/useBuildId.tsx"
  ]
},
```

Which build a directory like so:

```
package/
  components/
    Form/
      package.json // etc
  hooks/
    useBuildId/
      package.json // etc
  dist
    declarations
      src
        components
          Form/
            Form.d.ts
            Form.d.ts.map
        hooks
          useBuildId.d.ts
          useBuildId.d.ts.map
```

My problem is that VSCode will auto import Form like this: 
```ts
import Form from 'package/dist/declarations/src/components/Form/Form'
```
And I manually have to change it to
```ts
import Form from 'package/components/Form/Form'
```

I have a feeling like I have something configured wrong, maybe the declarationMap setting? Or is there a preconstruct option to inline .d.ts files with their respective packages, instead of separately in a declarations folder?

Any advice would be greatly appreciated.

**Comment by emmatown** [comment]
You can fix this by using the [`"moduleResolution": "bundler"` in TypeScript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler) which will respect the `exports` field.

**Comment by RossMcMillan92** [comment]
Thanks for the reply Emma!

Had a read and a play around but not having much luck with it. I think this would work if the consumers of our TS library were also using TS, but they are unfortunately still using JS. Could be wrong though, gonna play around some more.

As a workaround, we have an auto-fixing lint rule that removes the `dist/declarations/src/` from our imports.

**Comment by hazzo** [comment]
Have the same issue @emmatown and `"moduleResolution": "bundler"` did not fixe it. For me it's happening with WebStorm.

Here it's the packaged we developed with preconstruct that it's giving this issue when importing: https://github.com/mrmilu/inversify-generator

**Comment by RossMcMillan92** [comment]
Yeah this was never fixed for us either. We have a custom eslint rule that auto-corrects the imports.
