### ISSUE TITLE
Remove `meow` package in favor of parseArgs from node:util

### ISSUE THREAD

**Issue by VanTanev** [preconstruct/preconstruct#598]
Hello,

Looking at the way `@preconstruct/cli` uses `meow`, it should be easy to replace it with the native [parseArgs](https://nodejs.org/docs/latest-v20.x/api/util.html#utilparseargsconfig) that is available since node v16.17.0 and v18.3.0 (although it's marked experimental there, it seems to work without issue. It has no experimental flag since version v20.0.0).

Given that there is no args parsing in `@preconstruct/cli`, it's also possible to directly use `process.argv`. 

Removing `meow` would remove 62 dependencies from the installation of `@preconstruct/cli`: https://npmgraph.js.org/?q=meow%407 - this is a whole 30% of all dependencies installed by `@preconstruct/cli`.

If there is interest in this from the maintainers, I can provide a PR. If not, please feel free to close this issue.

Cheers!

**Comment by emmatown** [comment]
A PR would be great, preferably just using `process.argv` directly and just printing the help text on `preconstruct --help`

**Comment by VanTanev** [comment]
> A PR would be great, preferably just using `process.argv` directly and just printing the help text on `preconstruct --help`

Done!

Also, is there interest in trying to slim down other dependencies? Looking at npm graph, some of the other candidates are `chalk` and `fast-glob`.

**Comment by emmatown** [comment]
Replacing `chalk` with `picocolors` sounds fine. Not sure what `fast-glob` would be replaced with since the experimental one added to node is definitely too new to require?

**Comment by VanTanev** [comment]
I'll give it a shake and see what I can come up with, might not be much. `picocolors` should be a straightforward replacement but everything else is a bit more dubious.

Which node versions are explicitly supported by preconstruct? Is it up to the oldest active LTS, which would be Node.JS v18?
