### ISSUE TITLE
Invalid Typescript declarations when building packages

### ISSUE THREAD

**Issue by CarlosCortizasCT** [preconstruct/preconstruct#601]
Hello ✋ 

We're experiencing an error in our monorepo regarding how Typescript files declarations are generated when building our packages we don't understand and, after investigating it for some days, we decided to raise this issue hoping for some help 🙏.

We've created [this repository](https://github.com/jaikumar-tj/preconstruct-playground) with the minimal code which reproduces the error.

We have three packages in that monorepo with this relationship:
![image](https://github.com/user-attachments/assets/a2aed19c-a051-4f35-93ce-01235af7bf9f)

The problem we see when we build the repo is that the `types.d.ts` file generated for the `Product` package looks like this:

![image](https://github.com/user-attachments/assets/6c40c98a-b0a3-4243-9914-beab88697c9c)

As you can see, **the import for the `Category` packages is correct, but the one for the `ProductType` package is not.**
Also, we see a `declarations-type` folder in the `product/dist` directory that seems weird and does not exist in the other packages.

This is how the `package.json` file of the `Product` package looks like:
![image](https://github.com/user-attachments/assets/df80e605-0274-4bc1-b245-f712dd25d60a)

Our theory is that maybe the packages names can be the root of the problem, but even if that's true, changing the name of the packages is not an option for us and we would like to know if there might be something broken in the build process of preconstruct that could be potentially fixed.

Thanks for your help 🙇

**Comment by Andarist** [comment]
Were you able to resolve the issue?

**Comment by CarlosCortizasCT** [comment]
> Were you able to resolve the issue?

Hi @Andarist ✋ 

No I weren't.

I'm closing this issue anyway because I don't this it's a Preconstruct problem but a Typescript one.
I already opened a similar [issue](https://github.com/microsoft/TypeScript/issues/60056) in TS repo but, unfortunately, I didn't get enough help to sort this out.
