### ISSUE TITLE
Batch errors from missing packages

### ISSUE THREAD

**Issue by Noviny** [preconstruct/preconstruct#74]
Sometimes when switching between packages we get an error like the following:

```js
{ [Error: ENOENT: no such file or directory, open '/Users/bconolly/Development/changesets/packages/get-dependents-graph/package.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/Users/bconolly/Development/changesets/packages/get-dependents-graph/package.json' }
```

This normally happens when switching between branches, and due to untracked files the directory for that package.json is left behind, then included in the preconstruct glob.

My **desired behaviour** would be to a) parse this error and provide guides on what to do based on the information above and b) if we hit this error, collect it, and check all other packages before throwing, so we can show this for multiple packages at once.

Was thinking of picking this up so feel free to assign it to me if you like.

**Comment by mitchellhamilton** [comment]
I fixed this recently and it even offers to delete the directories for you! you probably need to update preconstruct
