### ISSUE TITLE
How to enable sourcemaps for non-UMD builds?

### ISSUE THREAD

**Issue by justingrant** [preconstruct/preconstruct#83]
Can sourcemaps be enabled for non-UMD builds?  Looking at these lines below, it looks like the answer is "no" but wanted to make sure. Also, if "no", then why not?

https://github.com/preconstruct/preconstruct/blob/c5c40f12377fda3e5b4d2aaa06c37ec8516d2f92/packages/preconstruct/src/build/types.js#L16-L31

I'm asking because I'm trying to debug into a library ([react-select](https://github.com/JedWatson/react-select)) that uses preconstruct and sourcemaps aren't present which makes debugging harder. So I'm trying to figure out how to fork and PR this library to enable sourcemaps.

**Comment by mitchellhamilton** [comment]
Sorry for the slow response, we don't create source maps on non-UMD builds because they're slowish to create, generally not used by consumers and the output of non-UMD builds is intended to be readable enough that source maps are really necessary.
